MYOWN_CMS_WEBSITE/Controllers/AjaxData/SubmitTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MYOWN_CMS_WEBSITE.Class;
using System.Net.Http;
using System.Web.Script.Serialization;
using System.IO;
using System.Drawing;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace MYOWN_CMS_WEBSITE.Controllers.AjaxData
{
    public partial class AjaxDataController : Controller
    {
        #region SubmitType
        [HttpPost]
        public String SubmitType(string name_na, string name_en, string description)
        {
            var client = new HttpClient();

            var response_save = client.PostAsJsonAsync(DataFactory.SUBMIT_DRINK_TYPE, EncryptDecryptAlgorithm.EncryptData(
            JsonConvert.SerializeObject(new Object[1]{
                new
                    {
                        name_na = name_na,
                        name_en = name_en,
                        description = description,

                    }}), DataFactory.ENC_ADKEY)).Result;

            if (response_save.IsSuccessStatusCode)
            {
                var result = response_save.Content.ReadAsStringAsync().Result;
                ViewBag.result = result;
                return result;
            }
            else
            {
                return "ERROR:003";
            }
        }
        #endregion
    }
}

MYOWN_CMS_WEBSITE/Controllers/SystemAccount/SearchAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MYOWN_CMS_WEBSITE.Controllers
{
    public partial class SystemAccountController : Controller
    {
        public ActionResult SearchAccount()
        {
            return View();
        }
    }
}

MYOWN_CMS_WEBSITE/Controllers/SystemAccount/SystemAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MYOWN_CMS_WEBSITE.Class;

namespace MYOWN_CMS_WEBSITE.Controllers
{
    public partial class SystemAccountController : Controller
    {
        public ActionResult NewSystemAccount(int? id)
        {
            if (id == null) id = 0;

            if (id != 0)
            {
                var client = new HttpClient();
                var response = client.PostAsJsonAsync(DataFactory.REQUEST_SYSTEM_ACCOUNT_API,
                    EncryptDecryptAlgorithm.EncryptData(new JavaScriptSerializer().Serialize(new Object[1]{
                        new {
                                id = id,
                    }}), DataFactory.ENC_ADKEY)).Result;

                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync().Result;
                    if (result.StartsWith(DataFactory.CODE_ERROR))
                    {
                        string[] error = result.Split(':');
                        ViewBag.error = error[1];
                        return View();
                    }
                    ViewBag.result = result;
                }
                else
                {
                    ViewBag.err = "ERROR:003";
                }

            }

            ViewBag.id = id;
            return View();
        }
    }
}

MYOWN_CMS_WEBSITE/Views/SystemAccount/NewSystemAccount.cshtml
@{
    ViewBag.Title = "NewSystemAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int id = ViewBag.id;
}

@section PageCss{
    
}

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <span class="caption-subject bold uppercase"> NEW SYSTEM ACCOUNT</span>
        </div>
    </div>    
    <form id="system_account">
        <div class="row">
            <div class="col-sm-6">
                <div class="col-md-4 col-sm-6">
                    <div class="dropzone" data-upload_title="profile_image" data-name="Profile_Image" data-image_check_name="1" data-has_image="" id="profile_image"></div>
                    <label class="control-label ">PROFILE IMAGE</label>
                </div>
            </div>
            <div class="col-sm-4">
                <b class="text-center col-sm-12 form-group">CREATE ACCOUNT</b>
                <div class="input-group form-group">                    
                    <span class="input-group-addon input-circle-left">
                        <i class="fa fa-user"></i>
                    </span>
                    <input type="text" id="username" class="form-control input-circle-right" placeholder="USERNAME">
                </div>
                <div class="input-group form-group">
                    <span class="input-group-addon input-circle-left">
                        <i class="fa fa-key"></i>
                    </span>
                    <input type="password" id="password" class="form-control input-circle-right" placeholder="PASSWORD">
                </div>
                <hr />
                <div class="form-group">
                    <label>FIRST NAME</label>
                    <input class="form-control" id="f_name" name="f_name" value="" />
                </div>
                <div class="form-group">
                    <label>LAST NAME</label>
                    <input class="form-control" id="l_name" name="l_name" value="" />
                </div>
                <div class="form-group">
                    <label>TELEPHONE</label>
                    <input class="form-control" id="telephone" name="telephone" value="" />
                </div>
                <div class="form-group">
                    <label>EMAIL</label>
                    <input class="form-control" id="email" name="email" type="email" value="" />
                </div>
            </div>
        </div>
        <button type="button" class="btn btn-info" id="submit_system_account">CREATE</button>
        <button type="button" class="btn btn-default" id="cancle">RESET</button>
    </form>
</div>


@section PageJavascriptPre{
    
}

@section PageJavascript{
<script type="text/javascript">
    $('#submit_system_account').on('click', function () {
        submitSystemAccount();
    });

    function submitSystemAccount() {

        var username = $('#username').val();
        var password = $('#password').val();
        var f_name = $('#f_name').val();
        var l_name = $('#l_name').val();
        var telephone = $('#telephone').val();
        var email = $('#email').val();

        App.blockUI();
        $.ajax({
        url: '@Url.Action("SubmitSystemAccount", "AjaxData")',
        type: 'POST',
        contentType: 'application/json; charset=utf-8',
        data: JSON.stringify({

            username: username,
            password: password,
            f_name: f_name,
            l_name: l_name,
            telephone: telephone,
            email: email,
        }),
        success: function (result) {
            App.unblockUI();

            if (result.startsWith("SUCCESS")) {

                bootbox.alert("SUCCESS", function () {
                    window.location.reload();
                });
            }
            else {
                bootbox.alert("Error: Data corrupt, " + result);
                return;
            }
        }
        });
    }
</script>

<script>
    // ======= DROBZONE ========= //
    $(".dropzone").each(function (index, element) {
        var title = $(element).data("upload_title");
        var selector_id = "#" + $(element).data("name");
        var ref_image_check = $(element).data("image_check_name");
        var filename = $(element).data("name"); //not use because can file name will auto generate

        var newDropzone = new Dropzone(selector_id, {
            url: "@Url.Action("AjaxUploadFile", "AjaxData")?path=system_account\\@id\\&filename=" + filename,
            maxFiles: 1,
            addRemoveLinks: true,
            acceptedFiles: ".jpg,.png,.gif,.jpeg",
            dictDefaultMessage: "<div><i class='fa fa-cloud-upload fa-3x'></i></div><div><b>" + title +"</b></div>",
            init: function () {
                this.on("complete", function (file) {
                    $(".dz-remove").html('<i class="fa fa-trash-o"></i> Remove');
                });
                this.on("addedfile", function (file) {
                    $(".dz-remove").html('<i class="fa fa-trash-o"></i> Remove');
                });
                this.on("maxfilesexceeded", function(file){
                    newDropzone.removeAllFiles();
                    newDropzone.options.maxFiles = 1;
                    newDropzone.addFile(file);
                });
            },
            success: function (file, response) {
                var jsonResult = JSON.parse(response);
                if (jsonResult["result"] == "1") {
                    file.previewElement.classList.add("dz-success");
                    image_json_data.push({ fileRef: ref_image_check, fileName: jsonResult["fileName"], fileUrl: jsonResult["fileUrl"] });
                }
                else {
                    file.previewElement.classList.add("dz-error");
                }
            },
            removedfile: function (file) {
                var _ref;
                if (file.previewElement) {
                    if ((_ref = file.previewElement) != null) {
                        _ref.parentNode.removeChild(file.previewElement);
                        $(image_json_data).each(function (index, item) {
                            if (item.fileRef === ref_image_check) {
                                image_json_data.splice(index, 1);
                            }
                        });
                    }
                }
            }
        });
        if ($(this).data('has_image') == 1){
            var mockFile = { name: 'Profile_Image.jpg', size: 102400 };
            newDropzone.emit("addedfile", mockFile);
            newDropzone.emit("thumbnail", mockFile, `@(MYOWN_CMS_WEBSITE.Class.DataFactory.URL_MYOWN_CONTENT_UPLOAD)system_account/@id/Profile_Image.jpg`);
            newDropzone.emit("complete", mockFile);

            newDropzone.files.push(mockFile);
            newDropzone.options.maxFiles = 0;

            image_json_data.push({ fileRef: ref_image_check, fileName: "", fileUrl: Profile_Image });
        }
        i++;

    });
</script>
}

MYOWN_CMS_WEBSITE/Views/SystemAccount/SearchAccount.cshtml
@{
    ViewBag.Title = "SearchAccount";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--BEGIN SEARCH BOX-->
<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-search font-green"></i>
            <span class="caption-subject font-green bold uppercase">SEARCH BOARD</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""></a>
        </div>
    </div>
    <div class="portlet-body">
        <div style="display:flex; align-items:center; justify-content:center; width: 100%">
            <input id="search_text" type="text" class="form-control" placeholder="Search for..." style="width:50%; height: 50px; font-size: 16px;" />
            <a class="btn btn-primary btn-lg" id="btn_search" style="margin-left:10px; height: 50px; line-height:1.65;"><i class="fa fa-search"></i> SEARCH</a>
            <a class="btn btn-default btn-lg" id="btn_cancel" style="margin-left:10px; height: 50px; line-height:1.65;"><i class="fa fa-close"></i> CANCEL</a>
        </div>
    </div>
</div>
<!--END SEARCH BOX-->
<!--BEGIN TABLE BOX-->
<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-car font-green"></i>
            <span class="caption-subject font-green bold uppercase">SYSTEM ACCOUNT</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""></a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-12 text-right" style="">
                <a class="btn btn-info" style="margin-bottom:10px; height: 32px;" name="btn_add_type" id=""><i class="fa fa-plus-circle"></i>&ensp;ADD BRAND</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-hover" id="search_table">
                    <thead>
                        <tr>
                            <th class="text-center">ID</th>
                            <th class="text-center">USER NAME</th>
                            <th class="text-center">FIRST NAME</th>
                            <th class="text-center">LAST NAME</th>
                            <th class="text-center">EMAIL</th>
                            <th class="text-center">TELEPHONE</th>
                            <th class="text-center">EDIT / DELETE</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--END TABLE BOX-->