MYOWN_CMS_WEBSITE/Controllers/Bar/NewBarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MYOWN_CMS_WEBSITE.Controllers
{
    public partial class BarController : Controller
    {
        public ActionResult NewBar()
        {
            return View();
        }
    }
}

MYOWN_CMS_WEBSITE/Controllers/Drink/NewDrinkTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MYOWN_CMS_WEBSITE.Controllers
{
    public partial class DrinkController : Controller
    {
        public ActionResult NewDrinkType()
        {
            return View();
        }
    }
}

MYOWN_CMS_WEBSITE/Controllers/SystemAccount/SearchAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MYOWN_CMS_WEBSITE.Controllers
{
    public partial class SystemAccountController : Controller
    {
        public ActionResult SearchAccount()
        {
            return View();
        }
    }
}

MYOWN_CMS_WEBSITE/Views/Shared/_Layout.cshtml
@{ 
    string[] cookie = Request.Cookies[MYOWN_CMS_WEBSITE.Class.DataFactory.COOKIE_UID].Value.Split(':');
}
﻿<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>MY OWN WEBSITE</title>

        <!-- BEGIN LAYOUT FIRST STYLES -->
        <!-- END LAYOUT FIRST STYLES -->
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="~/Content/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/css/components.min.css" rel="stylesheet" type="text/css"/>
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="~/Content/assets/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="~/Content/assets/css/components.min.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/css/plugins.min.css" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        @RenderSection("PageCss", required: false)
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link id="" href="~/Content/assets/css/layout/themes/dark4.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/css/layout/layout.css" rel="stylesheet" type="text/css" />
        <link href="~/Content/assets/css/custom.css" rel="stylesheet" type="text/css"/>
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" />

    </head>

    <body class="page-header-fixed page-content-white">
        <div class="page-header navbar navbar-fixed-top">
            <div class="page-header-inner">
                <!-- BEGIN LOGO -->
                <div class="page-logo" style="width:340px;"> 
                    <a href="@Url.Action("Index","Home")">
                        <img src="~/Content/assets/img/DW Logo_long.png" class="logo-default" style="height: 65px; margin-top:0px;" />
                    </a>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN NAV MENU -->
                <div class="top-right" >
                    <ul class="nav navbar-nav pull-right">
                        <li class="dropdown dropdown-user" style="margin-bottom:10px;">
                            <a href="#" class="dropdown-hover" data-toggle="dropdown" data-hover="dropdown">
                                <img alt="" class="img-circle" src="/Content/assets/img/profile.png" style="width:35px;"/>
                                <span class="username">@HttpUtility.UrlDecode(Request.Cookies[MYOWN_CMS_WEBSITE.Class.DataFactory.COOKIE_UNAME].Value)</span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default" >
                                <li>
                                    <a href="@Url.Action("Profile","Home")">Profile</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Logout","Signin")">Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- END NAV MENU -->
            </div>
        </div>

        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <div class="page-sidebar-wrapper" style="border:5px; border-color:#000000;">
                <div class="page-sidebar" style="background-color:#e6dddc;">
                    <h4 style="margin-left:50px;"> MENU BAR</h4>
                </div>
                <div class="page-sidebar navbar-collapse collapse" data-slide-speed="300" style="margin-top:40px;">
                    <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-hover-submenu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="300">

                        <!--  BAR  -->
                        <li class="nav-item start" style="height:64px;">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <span class="title" style="font-size:30px;"><i class="icon-plus"></i></span>
                                <span class="title" style="margin-left:30px; font-size:30px;"> BAR</span>
                                <span class="selected"></span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item start ">
                                    <a href="@Url.Action("NewBar","Bar")" class="nav-link ">
                                        <i class="icon-plus"></i>
                                        <span class="title">New Bar</span>
                                    </a>
                                </li>
                                <li class="nav-item start ">
                                    <a href="@Url.Action("SearchBar","Bar")" class="nav-link ">
                                        <i class="icon-screen-desktop"></i>
                                        <span class="title">Search Bar</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--  END BAR  -->

                        <!--  HOME  -->
                        <li class="nav-item start">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-home" ></i>
                                <span class="title" style="margin-left:30px;">HOME</span>
                                <span class="selected"></span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item start ">
                                    <a href="@Url.Action("Index", "Home")" class="nav-link ">
                                        <i class="icon-globe"></i>
                                        <span class="title">DashBoard</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--  END HOME  -->

                        <!--  ACCOUNT PROFILE  -->
                        <li class="nav-item start">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-user"></i>
                                <span class="title" style="margin-left:30px;">ACCOUNT</span>
                                <span class="selected"></span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item start ">
                                    <a href="@Url.Action("NewSystemAccount","SystemAccount")" class="nav-link ">
                                        <i class="icon-user"></i>
                                        <span class="title">Create Account</span>
                                    </a>
                                </li>
                                <li class="nav-item start ">
                                    <a href="@Url.Action("SearchAccount","SystemAccount")" class="nav-link ">
                                        <i class="icon-screen-desktop"></i>
                                        <span class="title">Search Account</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--  END ACCOUNT PROFILE  -->                        

                        <!--  DRINK TYPE  -->
                        <li class="nav-item start">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-plus"></i>
                                <span class="title" style="margin-left:30px;">DRINKs Type</span>
                                <span class="selected"></span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item start ">
                                    <a href="@Url.Action("NewDrinkType","Drink")" class="nav-link ">
                                        <i class="icon-plus"></i>
                                        <span class="title">New Drink Type</span>
                                    </a>
                                </li>
                                <li class="nav-item start ">
                                    <a href="@Url.Action("SearchDrinkType","Drink")" class="nav-link ">
                                        <i class="icon-screen-desktop"></i>
                                        <span class="title">Search Drink Type</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--  END DRINK TYPE  -->

                        <!--  DRINK BRAND  -->
                        <li class="nav-item start">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-plus"></i>
                                <span class="title" style="margin-left:30px;">DRINKs Brand</span>
                                <span class="selected"></span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item start ">
                                    <a href="@Url.Action("NewDrinkBrand","Drink")" class="nav-link ">
                                        <i class="icon-plus"></i>
                                        <span class="title">New Drinks Brand</span>
                                    </a>
                                </li>
                                <li class="nav-item start ">
                                    <a href="@Url.Action("SearchDrinkBrand","Drink")" class="nav-link ">
                                        <i class="icon-screen-desktop"></i>
                                        <span class="title">Search Drink Brand</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <!--  END DRINK Brand  -->

                    </ul>
                </div>
            </div>
            <!-- BEGIN PAGE CONTENT -->
            <div class="page-content-wrapper">
                <div class="page-content" style="min-height:1434px;">
                    @RenderSection("PageLink", required: false)
                    @RenderBody()
                </div>
            </div>
            <!-- BEGIN PAGE CONTENT -->
        </div>
        <!-- BEGIN CONTAINER -->


        <!-- BEGIN FOOTER -->
    <div class="container body-content">

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
        <!-- END FOOTER -->


    <!-- BEGIN CORE PLUGINS -->
    <script src="~/Content/assets/plugins/jquery.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/plugins/jquery-migrate.min.js" type="text/javascript">></script>
    <script src="~/Content/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/plugins/js.cookie.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/plugins/bootbox/bootbox.min.js" type="text/javascript"></script>
    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <script src="~/Content/assets/scripts/app.min.js" type="text/javascript"></script>
    <!-- BEGIN THEME LAYOUT SCRIPTS -->
    <script src="~/Content/assets/scripts/layout/layout.js" type="text/javascript"></script>
    <script src="~/Content/assets/scripts/layout/demo.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/scripts/layout/global/quick-sidebar.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/scripts/layout/global/quick-nav.min.js" type="text/javascript"></script>
    <!-- BEGIN PAGE PLUGINS -->
    @RenderSection("PageJavascriptPre", required: false)
    <!-- END PAGE PLUGINS -->

    <!-- BEGIN RENDER SCRIPT EACH PAGE -->
    @RenderSection("PageJavascript", required: false)
    <!-- END RENDER SCRIPT EACH PAGE -->

    @RenderSection("scripts", required: false)
        
</body>

</html>